// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqsdisrsrqmizuadvobe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxc2Rpc3JzcnFtaXp1YWR2b2JlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzOTAzMjEsImV4cCI6MjA1Njk2NjMyMX0.gWWsLa_l3Xw3vhn06KDKLx0ot3BlcWi0PQ9gpb-jKCs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);